device = "/dev/input/event9"

tick_interval_microseconds = 2000

min_speed = 0

min_deceleration = 1420

initial_speed = 600.0

speed_factor = 80.0

max_speed_increase_per_wheel_event = 600.0

max_speed_decrease_per_wheel_event = 0.0

damping = 3.1

use_braking = true

braking_dejitter_microseconds = 100000

braking_cut_off_speed = 1000.0

speed_decrease_per_braking = inf

use_mouse_movement_braking = true

mouse_movement_dejitter_distance = 200

max_mouse_movement_event_interval_microseconds = 50000

mouse_movement_braking_cut_off_speed = 200

speed_decrease_per_mouse_movement = inf
