/**
 * Feature page: looping auto-play demos and language toggle.
 */
// eslint-disable-next-line no-unused-vars
const FeaturePage = (() => {

// Source code for demo boxes.

const DEMO_SOURCE = {
  vertical:
`Smooth Scroll for Linux

A wheel is precise hardware, but most desktops treat it like a staircase:
one click, one jump, another click, another jump.

This daemon listens to the real wheel events before the desktop receives them.
It keeps your original intent, then sends a stream of small, timed scroll steps
through a virtual input device.

Slow wheel movement stays careful.
Fast wheel movement gets out of the way.
When your hand stops, the motion decays naturally instead of snapping still.

The result is not a browser trick.
It works across your Linux desktop: terminals, editors, file managers,
settings panels, chat clients, long web pages, and anything else that scrolls.

There is no browser extension to install.
There is no per-app setting to chase.
Tune the physics once, run the daemon, and the desktop feels calmer everywhere.

Open a terminal and the same motion is there.
Open a browser and the same motion is there.
Open a settings window and the same motion is there.
You do not have to relearn how to scroll in each app.

Watch the same document in the two panes.
The left pane receives raw wheel ticks.
The right pane receives the smoothed output generated by the physics engine.

The text is ordinary.
The difference is in the motion.

Notice the left pane steps downward.
Notice the right pane glides through the same distance.
That is the whole product promise, made visible.${buildVerticalDemoAppendix()}`,

  horizontal:
`Drag View sample canvas

Row      Workspace item                                  Status       Horizontal detail
01       Kernel notes                                    Read         evdev, uinput, virtual device, high resolution wheel events
02       Editor buffer                                   Active       long line preview, diagnostics, change markers, branch comparison
03       File manager                                    Open         deeply nested folders, wide filenames, modified timestamps, permissions
04       Settings panel                                  Tuned        damping, acceleration, braking, free spin, drag view, passthrough
05       Terminal output                                 Running      package build logs, compiler diagnostics, release artifacts, checksums
06       Browser article                                 Reading      paragraphs, tables, code snippets, release notes, references
07       Spreadsheet                                     Wide         columns A through Z, frozen labels, imported measurements, chart data
08       Design review                                   Inspecting   spacing, alignment, contrast, language switching, responsive behavior

Hold the Drag View key.
Move the mouse.
The pointer movement becomes scrolling, so wide or tall content is easy to scan.

${buildHorizontalDemoRows()}`,
};

function buildVerticalDemoAppendix() {
  const patterns = [
    ['Terminal work', 'Read build logs without losing the line you were following.', 'Small wheel input moves carefully through compiler diagnostics.', 'Fast wheel input covers the long quiet stretches between warnings.'],
    ['Editor work', 'Scan source code, diffs, and review notes with the same physical feel.', 'The daemon does not care which toolkit owns the scroll view.', 'It emits ordinary input events, just shaped with better timing.'],
    ['Browser work', 'Long articles stop feeling like a staircase.', 'Short nudges stay short, quick bursts travel farther.', 'Momentum fades instead of snapping still at the end of a gesture.'],
    ['File manager work', 'Move through long folders without overshooting every tenth item.', 'The same damping applies to icon grids, list views, and details panes.', 'A single system setting can make every scrollable surface calmer.'],
    ['Settings work', 'Tune acceleration, damping, braking, and drag view once.', 'Export TOML when the curve feels right.', 'Restart the daemon and the desktop inherits the new motion.'],
    ['Free Spin work', 'Hold the key while a page is moving.', 'The scroll continues at a steady cruise.', 'Release the key and normal damping returns.'],
    ['Drag View work', 'Hold the key and move the mouse through wide panes.', 'Horizontal and vertical movement become scroll input.', 'Tiny scrollbars are no longer the only path through large surfaces.'],
    ['Daily work', 'The point is not spectacle.', 'The point is that the desktop stops interrupting your hand.', 'Motion becomes continuous enough to disappear.'],
  ];

  const sections = Array.from({ length: 72 }, (_, index) => patterns[index % patterns.length]);

  return sections.map((lines, index) => {
    const sectionNo = String(index + 1).padStart(2, '0');
    return [
      '',
      `Demo section ${sectionNo}: ${lines[0]}`,
      lines[1],
      lines[2],
      lines[3],
      'The content keeps going so long inertial demos never hit a hard visual stop.',
      'Line numbers continue normally because this is one generated document.',
    ].join('\n');
  }).join('\n');
}

function buildHorizontalDemoRows() {
  const names = ['Trace output', 'Patch review', 'Release matrix', 'Wayland notes', 'Device table', 'Scrolling lab'];
  const statuses = ['Queued', 'Reading', 'Tuned', 'Active', 'Measured', 'Ready'];
  return Array.from({ length: 160 }, (_, i) => {
    const row = i + 9;
    const name = names[i % names.length];
    const status = statuses[i % statuses.length];
    const detail = 'extended columns for horizontal drag view, timing samples, movement deltas, scroll ids, and virtual device reports';
    return `${String(row).padStart(2, '0')}       ${name.padEnd(46)} ${status.padEnd(12)} ${detail}`;
  }).join('\n');
}

// Demo scenarios, separate from configurator Scenarios.

const DemoScenarios = {
  smooth: {
    events: Array.from({ length: 6 }, (_, i) => ({ timeMs: i * 30, positive: true })),
    maxDurationMs: 3000,
    enterDelayMs: 500,
    pauseMs: 500,
  },
  adaptiveSlow: {
    events: Array.from({ length: 5 }, (_, i) => ({ timeMs: i * 50, positive: true })),
    maxDurationMs: 2000,
    enterDelayMs: 500,
    pauseMs: 500,
  },
  adaptiveFast: {
    events: Array.from({ length: 6 }, (_, i) => ({ timeMs: i * 15, positive: true })),
    maxDurationMs: 3000,
    enterDelayMs: 500,
    pauseMs: 500,
  },
  adaptiveBurst: {
    events: [
      ...Array.from({ length: 7 }, (_, i) => ({ timeMs: i * 8, positive: true })),
      ...Array.from({ length: 7 }, (_, i) => ({ timeMs: 300 + i * 8, positive: true })),
      ...Array.from({ length: 7 }, (_, i) => ({ timeMs: 600 + i * 8, positive: true })),
      ...Array.from({ length: 7 }, (_, i) => ({ timeMs: 900 + i * 8, positive: true })),
      ...Array.from({ length: 7 }, (_, i) => ({ timeMs: 1200 + i * 8, positive: true })),
    ],
    maxDurationMs: 10000,
    enterDelayMs: 500,
    pauseMs: 500,
  },
  freeSpin: {
    events: Array.from({ length: 5 }, (_, i) => ({ timeMs: i * 25, positive: true })),
    maxDurationMs: 3000,
    freeSpinStartMs: 200,
    freeSpinEndMs: 1500,
    enterDelayMs: 500,
    pauseMs: 500,
  },
  dragView: {
    events: Array.from({ length: 5 }, (_, i) => ({ timeMs: i * 50, positive: true })),
    maxDurationMs: 4000,
    dragViewPressMs: 400,
    dragViewReleaseMs: 2200,
    mouseMovements: [
      { timeMs: 500,  relX: 25,  relY: 0 },
      { timeMs: 520,  relX: 25,  relY: 0 },
      { timeMs: 540,  relX: 25,  relY: 0 },
      { timeMs: 560,  relX: 25,  relY: 0 },
      { timeMs: 580,  relX: 25,  relY: 0 },
      { timeMs: 600,  relX: 25,  relY: 0 },
      { timeMs: 620,  relX: 25,  relY: 0 },
      { timeMs: 640,  relX: 25,  relY: 0 },
      { timeMs: 660,  relX: 25,  relY: 0 },
      { timeMs: 680,  relX: 25,  relY: 0 },
      { timeMs: 700,  relX: 25,  relY: 0 },
      { timeMs: 720,  relX: 25,  relY: 0 },
      { timeMs: 740,  relX: 25,  relY: 0 },
      { timeMs: 760,  relX: 25,  relY: 0 },
      { timeMs: 780,  relX: 25,  relY: 0 },
      { timeMs: 800,  relX: 25,  relY: 0 },
      { timeMs: 820,  relX: 25,  relY: 0 },
      { timeMs: 840,  relX: 25,  relY: 0 },
      { timeMs: 860,  relX: 25,  relY: 0 },
      { timeMs: 880,  relX: 25,  relY: 0 },
      { timeMs: 900,  relX: 25,  relY: 0 },
      { timeMs: 920,  relX: 25,  relY: 0 },
      { timeMs: 940,  relX: 25,  relY: 0 },
      { timeMs: 960,  relX: 25,  relY: 0 },
      { timeMs: 980,  relX: 25,  relY: 0 },
      { timeMs: 1100,  relX: 0,  relY: 15 },
      { timeMs: 1120,  relX: 0,  relY: 15 },
      { timeMs: 1140,  relX: 0,  relY: 15 },
      { timeMs: 1160,  relX: 0,  relY: 15 },
      { timeMs: 1180,  relX: 0,  relY: 15 },
      { timeMs: 1300,  relX: 0,  relY: -15 },
      { timeMs: 1320,  relX: 0,  relY: -15 },
      { timeMs: 1340,  relX: 0,  relY: -15 },
      { timeMs: 1360,  relX: 0,  relY: -15 },
      { timeMs: 1380,  relX: 0,  relY: -15 },
      { timeMs: 1400,  relX: 0,  relY: -15 },
      { timeMs: 1420,  relX: 0,  relY: -15 },
      { timeMs: 1440,  relX: 0,  relY: -15 },
      { timeMs: 1460,  relX: 0,  relY: -15 },
      { timeMs: 1480,  relX: 0,  relY: -15 },
      { timeMs: 1600,  relX: -25,  relY: 0 },
      { timeMs: 1620,  relX: -25,  relY: 0 },
      { timeMs: 1640,  relX: -25,  relY: 0 },
      { timeMs: 1660,  relX: -25,  relY: 0 },
      { timeMs: 1680,  relX: -25,  relY: 0 },
      { timeMs: 1700,  relX: -25,  relY: 0 },
      { timeMs: 1720,  relX: -25,  relY: 0 },
      { timeMs: 1740,  relX: -25,  relY: 0 },
      { timeMs: 1760,  relX: -25,  relY: 0 },
      { timeMs: 1780,  relX: -25,  relY: 0 },
      { timeMs: 1800,  relX: -25,  relY: 0 },
      { timeMs: 1820,  relX: -25,  relY: 0 },
      { timeMs: 1840,  relX: -25,  relY: 0 },
      { timeMs: 1860,  relX: -25,  relY: 0 },
      { timeMs: 1880,  relX: -25,  relY: 0 },
      { timeMs: 1900,  relX: -25,  relY: 0 },
      { timeMs: 1920,  relX: -25,  relY: 0 },
      { timeMs: 1940,  relX: -25,  relY: 0 },
      { timeMs: 1960,  relX: -25,  relY: 0 },
      { timeMs: 1980,  relX: -25,  relY: 0 },
      { timeMs: 2000,  relX: -25,  relY: 0 },
      { timeMs: 2020,  relX: -25,  relY: 0 },
      { timeMs: 2040,  relX: -25,  relY: 0 },
      { timeMs: 2060,  relX: -25,  relY: 0 },
      { timeMs: 2080,  relX: -25,  relY: 0 },
    ],
    enterDelayMs: 500,
    pauseMs: 500,
  },
};

// Helpers.

function buildFeatureEvents(scenario) {
  // Only build feature-specific events (free-spin, drag-view, mouse movements).
  // Scroll events from scenario.events are already handled by PhysicsEngine.simulate.
  const events = [];

  if (scenario.freeSpinStartMs != null) {
    events.push({ timeUs: scenario.freeSpinStartMs * 1000, type: 'free-spin', value: 1 });
  }
  if (scenario.freeSpinEndMs != null) {
    events.push({ timeUs: scenario.freeSpinEndMs * 1000, type: 'free-spin', value: 0 });
  }
  if (scenario.dragViewPressMs != null) {
    events.push({ timeUs: scenario.dragViewPressMs * 1000, type: 'drag-view', value: 1 });
  }
  if (scenario.dragViewReleaseMs != null) {
    events.push({ timeUs: scenario.dragViewReleaseMs * 1000, type: 'drag-view', value: 0 });
  }
  if (scenario.mouseMovements) {
    for (const m of scenario.mouseMovements) {
      if (m.relX != null && m.relX !== 0) {
        events.push({ timeUs: m.timeMs * 1000, type: 'rel-x', value: m.relX });
      }
      if (m.relY != null && m.relY !== 0) {
        events.push({ timeUs: m.timeMs * 1000, type: 'rel-y', value: m.relY });
      }
    }
  }

  return events.sort((a, b) => a.timeUs - b.timeUs);
}

function buildPaddedTimeline(physicsTimelineOrRaw, scenario, pixelsPerUnit) {
  const enterDelay = scenario.enterDelayMs || 0;
  const pause = scenario.pauseMs || 0;

  // Accept either physics timeline (array of objects) or pre-built scroll timeline
  let verticalTl, horizontalTl;
  if (physicsTimelineOrRaw.length > 0 && physicsTimelineOrRaw[0].scrollTop != null) {
    // Already a scroll timeline
    verticalTl = physicsTimelineOrRaw;
    horizontalTl = [];
  } else {
    verticalTl = physicsTimelineToScrollTimeline(physicsTimelineOrRaw, pixelsPerUnit);
    horizontalTl = physicsTimelineToHorizontalScrollTimeline(physicsTimelineOrRaw, pixelsPerUnit);
  }

  const scrollTl = addIdleHoldKeyframes(mergeScrollTimelines(verticalTl, horizontalTl));
  const lastPhysicsMs = scrollTl.length > 0 ? scrollTl[scrollTl.length - 1].timeMs : 0;
  const lastV = scrollTl.length > 0 ? scrollTl[scrollTl.length - 1].scrollTop : 0;
  const lastH = scrollTl.length > 0 ? scrollTl[scrollTl.length - 1].scrollLeft : 0;

  const timeline = [];

  // Phase 1: Enter delay (idle at 0)
  if (enterDelay > 0) {
    timeline.push({ timeMs: 0, scrollTop: 0, scrollLeft: 0 });
    timeline.push({ timeMs: enterDelay, scrollTop: 0, scrollLeft: 0 });
  }

  // Phase 2: Physics (offset by enterDelay)
  for (const pt of scrollTl) {
    timeline.push({
      timeMs: enterDelay + pt.timeMs,
      scrollTop: pt.scrollTop,
      scrollLeft: pt.scrollLeft || 0,
    });
  }

  // Phase 3: hold the final position. When the loop wraps, scrollTop returns
  // instantly to the first keyframe.
  const totalMs = enterDelay + lastPhysicsMs + pause;

  timeline.push({
    timeMs: totalMs,
    scrollTop: lastV,
    scrollLeft: lastH,
  });

  return { timeline, totalMs };
}

function extendPaddedTimeline(timeline, targetTotalMs) {
  const last = timeline[timeline.length - 1];
  if (last.timeMs < targetTotalMs) {
    timeline.push({
      timeMs: targetTotalMs,
      scrollTop: last.scrollTop,
      scrollLeft: last.scrollLeft || 0,
    });
  }
}

function addIdleHoldKeyframes(timeline) {
  if (timeline.length < 2) return timeline;

  const idleGapMs = 64;
  const result = [timeline[0]];

  for (let i = 0; i < timeline.length - 1; i++) {
    const a = timeline[i];
    const b = timeline[i + 1];
    const scrollLeftA = a.scrollLeft || 0;
    const scrollLeftB = b.scrollLeft || 0;
    const hasMotion = a.scrollTop !== b.scrollTop || scrollLeftA !== scrollLeftB;
    const holdTimeMs = b.timeMs - 1;

    if (hasMotion && b.timeMs - a.timeMs > idleGapMs && holdTimeMs > a.timeMs) {
      result.push({ timeMs: holdTimeMs, scrollTop: a.scrollTop, scrollLeft: scrollLeftA });
    }

    result.push(b);
  }

  return result;
}

function buildPaddedTimelineEvents(scenario) {
  const enterDelay = scenario.enterDelayMs || 0;
  const events = [];

  for (const evt of scenario.events) {
    events.push({
      timeMs: enterDelay + evt.timeMs,
      type: evt.positive !== false ? 'scroll-down' : 'scroll-up',
    });
  }

  if (scenario.freeSpinStartMs != null) {
    events.push({ timeMs: enterDelay + scenario.freeSpinStartMs, type: 'free-spin' });
  }
  if (scenario.freeSpinEndMs != null) {
    events.push({ timeMs: enterDelay + scenario.freeSpinEndMs, type: 'free-spin-release' });
  }
  if (scenario.dragViewPressMs != null) {
    events.push({ timeMs: enterDelay + scenario.dragViewPressMs, type: 'drag-view' });
  }
  if (scenario.dragViewReleaseMs != null) {
    events.push({ timeMs: enterDelay + scenario.dragViewReleaseMs, type: 'drag-view-release' });
  }
  if (scenario.mouseMovements && scenario.mouseMovements.length > 0) {
    for (const m of scenario.mouseMovements) {
      if ((m.relX || 0) !== 0 || (m.relY || 0) !== 0) {
        events.push({ timeMs: enterDelay + m.timeMs, type: 'mouse-move' });
      }
    }
  }

  return events.sort((a, b) => a.timeMs - b.timeMs);
}

function prefersReducedMotion() {
  return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

const TIMELINE_ICONS = {
  'scroll-up':         '<svg viewBox="0 0 10 10" width="10" height="10"><path d="M5 1L1.5 5H4v4h2V5h2.5z" fill="currentColor"/></svg>',
  'scroll-down':       '<svg viewBox="0 0 10 10" width="10" height="10"><path d="M5 9L1.5 5H4V1h2v4h2.5z" fill="currentColor"/></svg>',
  'scroll-right':      '<svg viewBox="0 0 10 10" width="10" height="10"><path d="M9 5L5 1.5V4H1v2h4v2.5z" fill="currentColor"/></svg>',
  'scroll-left':       '<svg viewBox="0 0 10 10" width="10" height="10"><path d="M1 5L5 1.5V4h4v2H5v2.5z" fill="currentColor"/></svg>',
  'free-spin':         '<svg viewBox="0 0 10 10" width="10" height="10"><path d="M5.5 1A4 4 0 1 1 1.3 6h1.5a2.5 2.5 0 1 0 2-2.9L3.5 5h3V2z" fill="currentColor"/></svg>',
  'free-spin-release': '<svg viewBox="0 0 10 10" width="10" height="10"><path d="M5.5 1A4 4 0 1 1 1.3 6h1.5a2.5 2.5 0 1 0 2-2.9L3.5 5h3V2z" fill="currentColor" opacity="0.6"/></svg>',
  'drag-view':         '<svg viewBox="0 0 10 10" width="10" height="10"><path d="M5 0v3.5M5 6.5v3.5M0 5h3.5M6.5 5H10" stroke="currentColor" stroke-width="1.2" fill="none"/><circle cx="5" cy="5" r="1.5" fill="currentColor"/></svg>',
  'drag-view-release': '<svg viewBox="0 0 10 10" width="10" height="10"><path d="M5 0v3.5M5 6.5v3.5M0 5h3.5M6.5 5H10" stroke="currentColor" stroke-width="1.2" fill="none" opacity="0.6"/><circle cx="5" cy="5" r="1.5" fill="currentColor" opacity="0.6"/></svg>',
  'mouse-move':        '<svg viewBox="0 0 10 10" width="10" height="10"><path d="M5 2v6M2 5h6" stroke="currentColor" stroke-width="1.2" stroke-linecap="round"/></svg>',
};

// ScrollDemo component.

class ScrollDemo {
  constructor(container, options) {
    this.container = container;
    this.timeline = options.timeline;
    this.totalMs = options.totalMs;
    this.hasHorizontalScroll = options.hasHorizontalScroll || false;
    this.onProgress = options.onProgress || null;
    this._animFrame = null;
    this._startTime = 0;

    this._build(options.sourceCode);
  }

  _build(sourceCode) {
    this.container.innerHTML = '';

    const content = document.createElement('div');
    content.className = 'demo-box-content' + (this.hasHorizontalScroll ? ' has-horizontal-scroll' : '');

    const pre = document.createElement('pre');
    pre.innerHTML = renderCodeWithLineNumbers(sourceCode);
    content.appendChild(pre);
    this.container.appendChild(content);

    this._content = content;
  }

  play() {
    if (prefersReducedMotion()) {
      const last = this.timeline[this.timeline.length - 1];
      this._content.scrollTop = last.scrollTop;
      this._content.scrollLeft = last.scrollLeft || 0;
      if (this.onProgress) this.onProgress(this.totalMs);
      return;
    }

    this._startTime = performance.now();
    this._animFrame = requestAnimationFrame(this._animate.bind(this));
  }

  stop() {
    if (this._animFrame) {
      cancelAnimationFrame(this._animFrame);
      this._animFrame = null;
    }
    this._content.scrollTop = 0;
    this._content.scrollLeft = 0;
  }

  _animate(now) {
    const elapsed = now - this._startTime;
    const tl = this.timeline;
    const totalMs = this.totalMs;

    // Loop: wrap elapsed time
    const loopElapsed = elapsed % totalMs;

    // Find bracketing entries
    let i = 0;
    while (i < tl.length - 1 && tl[i + 1].timeMs <= loopElapsed) i++;

    if (i >= tl.length - 1) {
      const last = tl[tl.length - 1];
      this._content.scrollTop = last.scrollTop;
      if (last.scrollLeft != null) this._content.scrollLeft = last.scrollLeft;
      if (this.onProgress) this.onProgress(loopElapsed);
      this._animFrame = requestAnimationFrame(this._animate.bind(this));
      return;
    }

    const a = tl[i];
    const b = tl[i + 1];
    const t = (loopElapsed - a.timeMs) / (b.timeMs - a.timeMs);

    this._content.scrollTop = a.scrollTop + (b.scrollTop - a.scrollTop) * t;
    const scrollLeftA = a.scrollLeft || 0;
    const scrollLeftB = b.scrollLeft || 0;
    this._content.scrollLeft = scrollLeftA + (scrollLeftB - scrollLeftA) * t;

    if (this.onProgress) this.onProgress(loopElapsed);
    this._animFrame = requestAnimationFrame(this._animate.bind(this));
  }
}

// DemoTimeline component.

const activeTimelines = new Map();

class DemoTimeline {
  constructor(containerId, events, maxDurationMs) {
    this.container = document.getElementById(containerId);
    if (!this.container) return;
    this.events = events;
    this.maxDurationMs = maxDurationMs;
    this._build();
    activeTimelines.set(containerId, this);
  }

  _build() {
    this.container.innerHTML = '';

    const track = document.createElement('div');
    track.className = 'tl-track';

    const fill = document.createElement('div');
    fill.className = 'tl-fill';
    track.appendChild(fill);

    for (const evt of this.events) {
      const marker = document.createElement('div');
      marker.className = `tl-event type-${evt.type}`;
      marker.style.left = `${(evt.timeMs / this.maxDurationMs) * 100}%`;
      marker.innerHTML = `<span class="tl-event-icon">${TIMELINE_ICONS[evt.type] || TIMELINE_ICONS['scroll-up']}</span>`;
      marker.dataset.eventType = evt.type;
      marker.setAttribute('aria-label', this._eventLabel(evt));
      marker.setAttribute('title', this._eventLabel(evt));
      track.appendChild(marker);
    }

    const cursor = document.createElement('div');
    cursor.className = 'tl-cursor';
    cursor.style.left = '0%';
    track.appendChild(cursor);

    this.container.appendChild(track);

    // Legend: unique event types in order of first appearance
    const seen = new Set();
    const legendTypes = [];
    for (const evt of this.events) {
      if (!seen.has(evt.type)) {
        seen.add(evt.type);
        legendTypes.push(evt.type);
      }
    }
    const legend = document.createElement('div');
    legend.className = 'tl-legend';
    for (const type of legendTypes) {
      const item = document.createElement('span');
      item.className = `tl-legend-item type-${type}`;
      item.dataset.eventType = type;
      item.innerHTML = `<span class="tl-legend-icon">${TIMELINE_ICONS[type] || TIMELINE_ICONS['scroll-up']}</span><span class="tl-legend-label">${this._eventLabel({ type })}</span>`;
      legend.appendChild(item);
    }
    this.container.appendChild(legend);

    this._cursor = cursor;
    this._fill = fill;
    this._markers = track.querySelectorAll('.tl-event');
  }

  refreshLang() {
    if (!this.container) return;
    this.container.querySelectorAll('.tl-event').forEach(marker => {
      const label = this._eventLabel({ type: marker.dataset.eventType });
      marker.setAttribute('aria-label', label);
      marker.setAttribute('title', label);
    });
    this.container.querySelectorAll('.tl-legend-item').forEach(item => {
      const labelEl = item.querySelector('.tl-legend-label');
      if (labelEl) labelEl.textContent = this._eventLabel({ type: item.dataset.eventType });
    });
  }

  setProgress(elapsedMs) {
    if (!this.container) return;
    const pct = Math.min(elapsedMs / this.maxDurationMs, 1) * 100;
    this._cursor.style.left = `${pct}%`;
    this._fill.style.width = `${pct}%`;

    for (const marker of this._markers) {
      const eventPct = parseFloat(marker.style.left);
      marker.classList.toggle('passed', eventPct <= pct + 0.5);
    }
  }

  _eventLabel(evt) {
    const labels = {
      'scroll-up':         I18n.t('feature.timeline.scroll-up'),
      'scroll-down':       I18n.t('feature.timeline.scroll-down'),
      'scroll-right':      I18n.t('feature.timeline.scroll-right'),
      'scroll-left':       I18n.t('feature.timeline.scroll-left'),
      'free-spin':         I18n.t('feature.timeline.free-spin'),
      'free-spin-release': I18n.t('feature.timeline.free-spin-release'),
      'drag-view':         I18n.t('feature.timeline.drag-view'),
      'drag-view-release': I18n.t('feature.timeline.drag-view-release'),
      'mouse-move':        I18n.t('feature.timeline.mouse-move'),
    };
    return labels[evt.type] || evt.type;
  }
}

// AdaptiveCycler cycles through speed adaptive scenarios one at a time.

class AdaptiveCycler {
  constructor(containerEl, scenarios, defaultOptions, pixelsPerUnit) {
    this.containerEl = containerEl;
    this.scenarios = scenarios;
    this.currentIndex = 0;
    this._animFrame = null;
    this._startTime = 0;
    this._content = null;
    this._timelineInstance = null;

    // Pre-compute all scenario data
    this.scenarioData = scenarios.map(({ key, scenario, i18nKey }) => {
      const result = PhysicsEngine.simulate(defaultOptions, scenario,
        { events: buildFeatureEvents(scenario) });
      const { timeline: paddedTl, totalMs } = buildPaddedTimeline(
        result.timeline, scenario, pixelsPerUnit);
      const events = buildPaddedTimelineEvents(scenario);

      const lastPt = result.timeline.length > 0 ? result.timeline[result.timeline.length - 1] : null;
      const totalDistance = lastPt ? lastPt.totalDelta : 0;
      const eventCount = scenario.events.length;
      const avgDistance = eventCount > 0 ? Math.round(totalDistance / eventCount) : 0;

      return { key, scenario, i18nKey, paddedTl, totalMs, events, result, totalDistance, eventCount, avgDistance };
    });

    this._buildDemoBox();
    this._populateDataPanel();
    this._switchTo(0);
  }

  _buildDemoBox() {
    this.containerEl.innerHTML = '';
    const content = document.createElement('div');
    content.className = 'demo-box-content';
    const pre = document.createElement('pre');
    pre.innerHTML = renderCodeWithLineNumbers(DEMO_SOURCE.vertical);
    content.appendChild(pre);
    this.containerEl.appendChild(content);
    this._content = content;
  }

  _populateDataPanel() {
    for (const data of this.scenarioData) {
      document.getElementById(`adaptive-dist-${data.key}`).textContent = data.totalDistance;
      document.getElementById(`adaptive-events-${data.key}`).textContent = data.eventCount;
      document.getElementById(`adaptive-avg-${data.key}`).textContent = data.avgDistance;
    }
  }

  _switchTo(index) {
    this.currentIndex = index;
    const data = this.scenarioData[index];
    this._timelineInstance = new DemoTimeline('timeline-adaptive', data.events, data.totalMs);
    this._updateFocus();
  }

  _updateFocus() {
    const rows = document.querySelectorAll('.adaptive-data-row:not(.adaptive-data-header)');
    rows.forEach((row, i) => {
      row.classList.toggle('focused', i === this.currentIndex);
    });

    const label = document.getElementById('adaptive-demo-label');
    const i18nKey = this.scenarioData[this.currentIndex].i18nKey;
    label.setAttribute('data-i18n', i18nKey);
    label.textContent = I18n.t(i18nKey);
  }

  play() {
    if (prefersReducedMotion()) {
      this._switchTo(this.currentIndex);
      const data = this.scenarioData[this.currentIndex];
      const last = data.paddedTl[data.paddedTl.length - 1];
      if (last) this._content.scrollTop = last.scrollTop;
      if (this._timelineInstance) this._timelineInstance.setProgress(data.totalMs);
      return;
    }

    this._switchTo(this.currentIndex);
    this._startTime = performance.now();
    this._animFrame = requestAnimationFrame(this._animate.bind(this));
  }

  stop() {
    if (this._animFrame) {
      cancelAnimationFrame(this._animFrame);
      this._animFrame = null;
    }
    if (this._content) this._content.scrollTop = 0;
  }

  _animate(now) {
    const elapsed = now - this._startTime;
    const data = this.scenarioData[this.currentIndex];
    const tl = data.paddedTl;
    const totalMs = data.totalMs;

    if (elapsed >= totalMs) {
      this._content.scrollTop = 0;
      this._switchTo((this.currentIndex + 1) % this.scenarios.length);
      this._startTime = performance.now();
      this._animFrame = requestAnimationFrame(this._animate.bind(this));
      return;
    }

    let i = 0;
    while (i < tl.length - 1 && tl[i + 1].timeMs <= elapsed) i++;

    if (i >= tl.length - 1) {
      const last = tl[tl.length - 1];
      this._content.scrollTop = last.scrollTop;
    } else {
      const a = tl[i];
      const b = tl[i + 1];
      const t = (elapsed - a.timeMs) / (b.timeMs - a.timeMs);
      this._content.scrollTop = a.scrollTop + (b.scrollTop - a.scrollTop) * t;
    }

    if (this._timelineInstance) this._timelineInstance.setProgress(elapsed);

    this._animFrame = requestAnimationFrame(this._animate.bind(this));
  }

}

function renderCodeWithLineNumbers(code) {
  const lines = code.split('\n');
  return lines.map((line, i) =>
    `<span class="line-number">${i + 1}</span>${escapeHtml(line)}`
  ).join('\n');
}

function escapeHtml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function buildDefaultOptions() {
  const d = ParamSchema.getDefaultValues();
  return {
    smooth_mode: d.smooth_mode ?? 0,
    wheel_tick_distance: d.wheel_tick_distance ?? 120,
    tick_interval_microseconds: d.tick_interval_microseconds ?? 2000,
    min_deceleration: d.min_deceleration ?? 1420,
    max_deceleration: d.max_deceleration ?? 6000,
    initial_speed: d.initial_speed ?? 600,
    speed_factor: d.speed_factor ?? 40,
    speed_smooth_window_microseconds: d.speed_smooth_window_microseconds ?? 200000,
    max_speed_change_lowerbound: d.max_speed_change_lowerbound ?? 512,
    min_speed_change_upperbound: d.min_speed_change_upperbound ?? 512,
    min_speed_change_ratio: d.min_speed_change_ratio ?? 0.0625,
    max_speed_change_ratio: d.max_speed_change_ratio ?? 0.5,
    damping: d.damping ?? 3.1,
    use_reverse_scroll_braking: d.use_reverse_scroll_braking ?? true,
    max_reverse_scroll_braking_microseconds: d.max_reverse_scroll_braking_microseconds ?? 100000,
    max_reverse_scroll_braking_times: d.max_reverse_scroll_braking_times ?? 3,
    drag_view_activation_mode: d.drag_view_activation_mode ?? 0,
    drag_view_click_timeout_milliseconds: d.drag_view_click_timeout_milliseconds ?? 200,
    drag_view_speed: d.drag_view_speed ?? 3,
  };
}

function physicsTimelineToScrollTimeline(physicsTimeline, pixelsPerUnit) {
  return physicsTimeline.filter(pt => !pt.emittedH).map(pt => ({
    timeMs: pt.timeMs,
    scrollTop: pt.totalDelta * pixelsPerUnit,
  }));
}

function physicsTimelineToHorizontalScrollTimeline(physicsTimeline, pixelsPerUnit) {
  return physicsTimeline.filter(pt => pt.emittedH || pt.totalDeltaH > 0).map(pt => ({
    timeMs: pt.timeMs,
    scrollLeft: (pt.totalDeltaH || 0) * pixelsPerUnit,
  }));
}

function mergeScrollTimelines(verticalTl, horizontalTl) {
  const byTime = new Map();
  for (const pt of verticalTl) {
    byTime.set(pt.timeMs, { ...(byTime.get(pt.timeMs) || {}), timeMs: pt.timeMs, scrollTop: pt.scrollTop });
  }
  for (const pt of horizontalTl) {
    byTime.set(pt.timeMs, { ...(byTime.get(pt.timeMs) || {}), timeMs: pt.timeMs, scrollLeft: pt.scrollLeft });
  }

  let scrollTop = 0;
  let scrollLeft = 0;
  return Array.from(byTime.values())
    .sort((a, b) => a.timeMs - b.timeMs)
    .map(pt => {
      if (pt.scrollTop != null) scrollTop = pt.scrollTop;
      if (pt.scrollLeft != null) scrollLeft = pt.scrollLeft;
      return { timeMs: pt.timeMs, scrollTop, scrollLeft };
    });
}

function generateOffTimeline(scenario, pixelsPerUnit) {
  const timeline = [];
  let totalDelta = 0;
  for (const evt of scenario.events) {
    totalDelta += 120;
    timeline.push({ timeMs: evt.timeMs, scrollTop: totalDelta * pixelsPerUnit });
  }
  // Hold the final position. No deceleration for "OFF" mode.
  if (timeline.length > 0) {
    const lastTime = timeline[timeline.length - 1].timeMs;
    const lastScrollTop = timeline[timeline.length - 1].scrollTop;
    timeline.push({ timeMs: lastTime + 500, scrollTop: lastScrollTop });
  }
  return timeline;
}

// Looping auto-play on visibility.

class LoopingAutoPlay {
  constructor() {
    this._callbacks = new Map();
    this._visible = new Set();
    this._observer = new IntersectionObserver((entries) => {
      for (const entry of entries) {
        const el = entry.target;
        if (entry.isIntersecting) {
          if (!this._visible.has(el)) {
            this._visible.add(el);
            this._start(el);
          }
        } else {
          this._visible.delete(el);
          this._stop(el);
        }
      }
    }, { threshold: 0.3 });
  }

  observe(sectionEl, callback) {
    this._callbacks.set(sectionEl, callback);
    this._observer.observe(sectionEl);
  }

  _start(el) {
    const cb = this._callbacks.get(el);
    if (cb) cb();
  }

  _stop(el) {
    const cb = this._callbacks.get(el);
    if (cb && cb._stop) cb._stop();
  }

  disconnect() {
    this._observer.disconnect();
  }
}

// Language toggle.

function updateFeaturePageLang() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    el.textContent = I18n.t(el.dataset.i18n);
  });
  activeTimelines.forEach(timeline => timeline.refreshLang());
}

// Section indicator.

function initSectionIndicator() {
  const indicator = document.getElementById('section-indicator');
  const pips = indicator.querySelectorAll('.section-pip');
  const sections = document.querySelectorAll('.feature-section');

  let activeIdx = 0;

  const sectionObserver = new IntersectionObserver((entries) => {
    for (const entry of entries) {
      if (entry.isIntersecting) {
        entry.target.classList.add('is-visible');
      }
      if (entry.isIntersecting) {
        const idx = Array.from(sections).indexOf(entry.target);
        activeIdx = idx;
        pips.forEach((p, i) => p.classList.toggle('active', i === idx));
      }
    }
  }, { threshold: 0.4 });

  sections.forEach(s => sectionObserver.observe(s));

  pips.forEach(pip => {
    pip.addEventListener('click', (e) => {
      e.preventDefault();
      const target = document.querySelector(pip.getAttribute('href'));
      if (target) target.scrollIntoView({ behavior: 'smooth' });
    });
  });

  document.addEventListener('keydown', (e) => {
    if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp') return;
    if (e.target.closest('input, textarea, select, [contenteditable]')) return;

    e.preventDefault();
    let nextIdx;
    if (e.key === 'ArrowDown') {
      nextIdx = Math.min(activeIdx + 1, sections.length - 1);
    } else {
      nextIdx = Math.max(activeIdx - 1, 0);
    }
    if (nextIdx !== activeIdx) {
      sections[nextIdx].scrollIntoView({ behavior: 'smooth' });
    }
  });
}

// Init.

function init() {
  Nav.render('nav');
  updateFeaturePageLang();

  // Language toggle
  const langToggle = document.getElementById('lang-toggle');
  langToggle.addEventListener('click', () => {
    I18n.setLang(I18n.lang() === 'zh' ? 'en' : 'zh');
    langToggle.textContent = I18n.lang() === 'zh' ? 'EN' : '中文';
    document.documentElement.lang = I18n.lang();
    Nav.updateLang();
    updateFeaturePageLang();
  });

  // Set initial html lang
  document.documentElement.lang = I18n.lang();

  const defaultOptions = buildDefaultOptions();
  const pixelsPerUnit = 0.3;

  // Section 1: Smooth Scrolling, OFF vs ON.
  const smoothScenario = DemoScenarios.smooth;
  const smoothOnResult = PhysicsEngine.simulate(defaultOptions, smoothScenario,
    { events: buildFeatureEvents(smoothScenario) });
  const { timeline: smoothOnTl, totalMs: smoothOnMs } = buildPaddedTimeline(
    smoothOnResult.timeline, smoothScenario, pixelsPerUnit);
  const smoothOffRaw = generateOffTimeline(smoothScenario, pixelsPerUnit);
  const { timeline: smoothOffTl, totalMs: smoothOffMs } = buildPaddedTimeline(
    smoothOffRaw, smoothScenario, pixelsPerUnit);

  // Synchronize: both demos reset at the same time
  const smoothTotalMs = Math.max(smoothOnMs, smoothOffMs);
  extendPaddedTimeline(smoothOnTl, smoothTotalMs);
  extendPaddedTimeline(smoothOffTl, smoothTotalMs);

  const smoothEvents = buildPaddedTimelineEvents(smoothScenario);
  const tlSmoothOff = new DemoTimeline('timeline-smooth-off', smoothEvents, smoothTotalMs);
  const tlSmoothOn = new DemoTimeline('timeline-smooth-on', smoothEvents, smoothTotalMs);

  const demoSmoothOff = new ScrollDemo(document.getElementById('demo-smooth-off'),
    { sourceCode: DEMO_SOURCE.vertical, timeline: smoothOffTl, totalMs: smoothTotalMs,
      onProgress: (ms) => tlSmoothOff.setProgress(ms) });
  const demoSmoothOn = new ScrollDemo(document.getElementById('demo-smooth-on'),
    { sourceCode: DEMO_SOURCE.vertical, timeline: smoothOnTl, totalMs: smoothTotalMs,
      onProgress: (ms) => tlSmoothOn.setProgress(ms) });

  // Section 2: Speed Adaptive, cycling single demo.
  const adaptiveScenarios = [
    { key: 'slow', scenario: DemoScenarios.adaptiveSlow, i18nKey: 'feature.adaptive.slow' },
    { key: 'fast', scenario: DemoScenarios.adaptiveFast, i18nKey: 'feature.adaptive.fast' },
    { key: 'burst', scenario: DemoScenarios.adaptiveBurst, i18nKey: 'feature.adaptive.burst' },
  ];

  const adaptiveCycler = new AdaptiveCycler(
    document.getElementById('demo-adaptive'),
    adaptiveScenarios, defaultOptions, pixelsPerUnit);

  // Section 3: Free Spin.
  const fsScenario = DemoScenarios.freeSpin;
  const fsResult = PhysicsEngine.simulate(defaultOptions, fsScenario,
    { events: buildFeatureEvents(fsScenario) });
  const { timeline: fsTl, totalMs: fsTotalMs } = buildPaddedTimeline(
    fsResult.timeline, fsScenario, pixelsPerUnit);
  const fsEvents = buildPaddedTimelineEvents(fsScenario);
  const tlFreespin = new DemoTimeline('timeline-freespin-on', fsEvents, fsTotalMs);
  const demoFsOn = new ScrollDemo(document.getElementById('demo-freespin-on'),
    { sourceCode: DEMO_SOURCE.vertical, timeline: fsTl, totalMs: fsTotalMs,
      onProgress: (ms) => tlFreespin.setProgress(ms) });

  // Section 4: Drag View.
  const dvScenario = DemoScenarios.dragView;
  const dvResult = PhysicsEngine.simulate(defaultOptions, dvScenario,
    { events: buildFeatureEvents(dvScenario) });
  const { timeline: dvTl, totalMs: dvTotalMs } = buildPaddedTimeline(
    dvResult.timeline, dvScenario, pixelsPerUnit);
  const dvEvents = buildPaddedTimelineEvents(dvScenario);
  const tlDragView = new DemoTimeline('timeline-dragview', dvEvents, dvTotalMs);
  const demoDragView = new ScrollDemo(document.getElementById('demo-dragview'),
    { sourceCode: DEMO_SOURCE.horizontal, timeline: dvTl, totalMs: dvTotalMs,
      hasHorizontalScroll: true,
      onProgress: (ms) => tlDragView.setProgress(ms) });

  // Auto-play observer.
  const observer = new LoopingAutoPlay();

  // Section 1: Smooth
  const smoothCb = () => { demoSmoothOff.play(); demoSmoothOn.play(); };
  smoothCb._stop = () => { demoSmoothOff.stop(); demoSmoothOn.stop(); };
  observer.observe(document.getElementById('section-smooth'), smoothCb);

  // Section 2: Adaptive
  const adaptiveCb = () => adaptiveCycler.play();
  adaptiveCb._stop = () => adaptiveCycler.stop();
  observer.observe(document.getElementById('section-adaptive'), adaptiveCb);

  // Section 3: Free Spin
  const freespinCb = () => { demoFsOn.play(); };
  freespinCb._stop = () => demoFsOn.stop();
  observer.observe(document.getElementById('section-freespin'), freespinCb);

  // Section 4: Drag View
  const dragviewCb = () => { demoDragView.play(); };
  dragviewCb._stop = () => demoDragView.stop();
  observer.observe(document.getElementById('section-dragview'), dragviewCb);

  // Section indicator
  initSectionIndicator();
}

return { init, updateFeaturePageLang };

})();
